spring.application.name=API openweathermap

# Cole sua chave da OpenWeatherMap aqui
weather.api.key=3694c43151de7e02d06800ec12be83fa
weather.api.url=https://api.openweathermap.org/data/2.5/weather

# Libera o front-end para chamar o back-end (CORS)
server.port=8080
